"""HHB marketed-town buybox for Gate 7 Investor Sold.

Gate 7 universe = these cities only. Sold rows outside this set are dropped at
ingest (before row build / enrich / KPIs).

Operator contract (why, what sold CSV can filter, how to read provider KPIs):
`docs/BUYBOX.md`. Regenerate the town appendix with
`python backend/scripts/gen_buybox_doc.py` after editing this list.
"""

from __future__ import annotations

import re
from typing import FrozenSet, Optional

# Display spellings (including known scrape typos / aliases). Matching uses normalize_town().
_BUYBOX_TOWN_LABELS: tuple[str, ...] = (
    'Centereach',
    'Coram',
    'East Meadow',
    'Freeport',
    'Hempstead',
    'Hicksville',
    'Huntington Station',
    'Levittown',
    'Lindenhurst',
    'Massapequa Park',
    'Mastic Beach',
    'West Babylon',
    'Westbury',
    'East Setauket',
    'Setauket',
    'Amityville',
    'Baldwin',
    'Bethpage',
    'East Northport',
    'Farmingdale',
    'Huntington',
    'Massapequa',
    'Mastic',
    'Medford',
    'Merrick',
    'North Amityville',
    'North Babylon',
    'North Patchogue',
    'Northport',
    'Patchogue',
    'Port Jefferson',
    'Port Jefferson Station',
    'Roosevelt',
    'Seaford',
    'Selden',
    'Shirley',
    'Uniondale',
    'Wantagh',
    'Bayshore',
    'Bellmore',
    'Bellport',
    'Brentwood',
    'Central Islip',
    'Commack',
    'Copiague',
    'Deer Park',
    'East Patchogue',
    'East Rockaway',
    'Elmont',
    'Elwood',
    'Farmingville',
    'Hauppauge',
    'Holbrook',
    'Holtsville',
    'Islip Terrace',
    'Kings Park',
    'Lake Grove',
    'Lynbrook',
    'Malverne',
    'Middle Island',
    'Miller Place',
    'Nesconset',
    'North Lynbrook',
    'Oceanside',
    'Old Bethpage',
    'Oyster Bay',
    'Plainview',
    'Riverhead',
    'Rockville Centre',
    'Rocky Point',
    'Ronkonkoma',
    'Smithtown',
    'Sound Beach',
    'Syosset',
    'Valley Stream',
    'West Hempstead',
    'West Islip',
    'Yaphank',
    'Babylon',
    'Bayport',
    'Bellerose Terrace',
    'Blue Point',
    'Bohemia',
    'Brightwaters',
    'Brookhaven',
    'Calverton',
    'Carle Place',
    'Center Moriches',
    'Centerport',
    'Cold Spring Harbor',
    'Dix Hills',
    'East Islip',
    'East Marion',
    'East Moriches',
    'Eastport',
    'Floral Park',
    'Franklin Square',
    'Greenlawn',
    'Island Park',
    'Islandia',
    'Islip',
    'Manorville',
    'Mineola',
    'Mount Sinai',
    'New Hyde Park',
    'North New Hyde Park',
    'North Valley Stream',
    'Oakdale',
    'Port Washington',
    'Ridge',
    'Saint James',
    'Sayville',
    'South Hempstead',
    'Stony Brook',
    'Wading River',
    'West Sayville',
    'North Bellmore',
    'Amity Harbor',
    'E Farmingdale',
    'E Moriches',
    'Flanders',
    'Garden City',
    'Glen Cove',
    'Lake Ronkonkoma',
    'Lido Beach',
    'Long Beach',
    'Melville',
    'Moriches',
    'Mt Sinai',
    'North Baldwin',
    'South Floral Park',
    'South Huntington',
    'South Setauket',
    'St James',
    'Westhampton Beach',
    'Wheatley Heights',
    'Wyandanch',
    'Albertson',
    'Alden Manor',
    'Astoria',
    'Bay Shore',
    'Bayside',
    'Bayville',
    'Beechhurst',
    'Belle Harbor',
    'Bellerose',
    'Bellerose Village',
    'Blue Poin',
    'Breezy Point',
    'Broad Channel',
    'Brooklyn',
    'Brookville',
    'Cambria Heights',
    'Corona',
    'E Northport',
    'East Elmhurst',
    'East Massapequa',
    'East Northport,',
    'East Williston',
    'Elmhurst',
    'Far Rockaway',
    'Flushing',
    'Fort Salonga',
    'FRANKLIN SQUAR',
    'Garden City Park',
    'Garden City South',
    'GardenCity',
    'Glen Oaks',
    'Great River',
    'Greenvale',
    'Hauppaüge',
    'Hicksvill',
    'Hollis',
    'Howard Beach',
    'Huntington Bay',
    'Huntington,',
    'Inwood',
    'Jamaica',
    'Jericho',
    'Kew Gardens',
    'Latham',
    'Little Neck',
    'Lloyd Harbor',
    'Malba',
    'Manhasset',
    'Manhasset Hills',
    'Maspeth',
    'Matinecock',
    'Middle Village',
    'North Massapequa',
    'North Merrick',
    'North Sea',
    'Oakland Gardens',
    'Ocean Bay Park',
    'Ocean Beach',
    'Old Westbury',
    'Ozone Park',
    'Patchog',
    'Queens Village',
    'Ridgewood',
    'Rosedale',
    'Saint Albans',
    'Seiden',
    'Setauket- East Setauket',
    'South Farmingdale',
    'South Ozone Park',
    'South Richmond Hill',
    'Southold',
    'Springfield Gardens',
    'Stewart Manor',
    'StIslip',
    'Sunnyside',
    'Woodside',
    'N babylon',
    'W babylon',
    'Richmond Hill',
)

_TRAILING_PUNCT_RE = re.compile(r"[,;.]+$")
_WS_RE = re.compile(r"\s+")


def normalize_town(city: Optional[str]) -> str:
    """Normalize city for buybox membership (casefold, strip, collapse spaces)."""
    if city is None:
        return ""
    text = str(city).strip()
    text = _TRAILING_PUNCT_RE.sub("", text).strip()
    text = _WS_RE.sub(" ", text)
    return text.casefold()


BUYBOX_TOWNS: FrozenSet[str] = frozenset(normalize_town(t) for t in _BUYBOX_TOWN_LABELS)
BUYBOX_TOWN_COUNT: int = len(BUYBOX_TOWNS)


def in_buybox(city: Optional[str]) -> bool:
    """True when city matches a marketed-town allowlist entry."""
    key = normalize_town(city)
    return bool(key) and key in BUYBOX_TOWNS
