#!/usr/bin/env python3
"""
Audit REISift Tags for Past-Patches-generated tokens that should be removed before a clean rerun.

Keeps: List Purchased 8020, (8020) CC/SMS/DM, Skip Traced (not generated by closings/opps bundle).

Usage:
  python scripts/reisift_tag_cleanup_audit.py --ingest-dir _ingest_out/20260515T143340Z_podio_closings_opps/csv
  python scripts/reisift_tag_cleanup_audit.py --export path/to/reisift_contacts_export.csv
  python scripts/reisift_tag_cleanup_audit.py --export export.csv --ingest-dir _ingest_out/.../csv
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

import pandas as pd

# Tags appended to REISift Tags by marketing_mapper Past Patches (closings + CRM).
REMOVE_PREFIXES = (
    "(CLOSED) 8020",
    "(SF) UPDATED -",
    "(SF) STATUS -",
)

# Never flag for removal (native / marketing history — user keeps purchase date).
KEEP_PREFIXES = (
    "List Purchased 8020",
    "(8020) CC",
    "(8020) SMS",
    "(8020) DM",
    "Skip Traced",
)


def _split_tags(tags_str: str) -> list[str]:
    if not tags_str or (isinstance(tags_str, float) and pd.isna(tags_str)):
        return []
    return [t.strip() for t in str(tags_str).split(",") if t.strip()]


def classify_token(token: str) -> str:
    for p in KEEP_PREFIXES:
        if token.startswith(p):
            return "keep"
    for p in REMOVE_PREFIXES:
        if token.startswith(p):
            return "remove"
    return "other"


def audit_tags_column(series: pd.Series, label: str) -> None:
    remove_counter: Counter[str] = Counter()
    keep_counter: Counter[str] = Counter()
    rows_with_remove = 0
    total_rows = len(series)

    for tags_str in series:
        tokens = _split_tags(tags_str)
        has_remove = False
        for tok in tokens:
            cat = classify_token(tok)
            if cat == "remove":
                remove_counter[tok] += 1
                has_remove = True
            elif cat == "keep":
                keep_counter[tok] += 1
        if has_remove:
            rows_with_remove += 1

    print(f"\n=== {label} ===")
    print(f"Rows scanned: {total_rows}")
    print(f"Rows with at least one REMOVABLE tag: {rows_with_remove}")

    print("\n--- REMOVABLE tag families (delete from REISift Tags) ---")
    print("  (CLOSED) 8020 - M/YYYY   ← closings_status_tags.csv")
    print("  (SF) UPDATED - ...       ← salesforce_status_tags.csv")
    print("  (SF) STATUS - ...        ← salesforce_status_tags.csv")

    if remove_counter:
        print(f"\nUnique removable tokens: {len(remove_counter)}")
        print(f"Total removable token occurrences: {sum(remove_counter.values())}")
        print("\nTop removable tokens (by occurrence count):")
        for tok, cnt in remove_counter.most_common(50):
            print(f"  [{cnt:5d}] {tok}")
        if len(remove_counter) > 50:
            print(f"  ... and {len(remove_counter) - 50} more unique tokens")
    else:
        print("\nNo removable Past-Patches tags found in this file.")

    print("\n--- KEEP (do not remove) — sample counts ---")
    for tok, cnt in keep_counter.most_common(10):
        print(f"  [{cnt:5d}] {tok}")
    if not keep_counter:
        print("  (none found in this export)")


def load_ingest_tags(ingest_dir: Path) -> pd.Series:
    closings = ingest_dir / "closings_status_tags.csv"
    sf = ingest_dir / "salesforce_status_tags.csv"
    tags: list[str] = []
    if closings.is_file():
        df = pd.read_csv(closings)
        if "tag" in df.columns:
            tags.extend(df["tag"].dropna().astype(str).tolist())
    if sf.is_file():
        df = pd.read_csv(sf)
        if "salesforce_tag" in df.columns:
            tags.extend(df["salesforce_tag"].dropna().astype(str).tolist())
    if not tags:
        raise FileNotFoundError(f"No tag columns in {ingest_dir}")
    return pd.Series([",".join(tags)] * 1)  # manifest only


def print_ingest_manifest(ingest_dir: Path) -> None:
    closings = ingest_dir / "closings_status_tags.csv"
    sf = ingest_dir / "salesforce_status_tags.csv"
    print(f"\n=== Ingest manifest: {ingest_dir} ===")

    if closings.is_file():
        df = pd.read_csv(closings)
        unique = sorted(df["tag"].dropna().unique()) if "tag" in df.columns else []
        print(f"closings_status_tags.csv: {len(df)} rows, {len(unique)} unique (CLOSED) month tokens")
        for t in unique:
            print(f"  {t}")

    if sf.is_file():
        df = pd.read_csv(sf)
        col = "salesforce_tag"
        if col in df.columns:
            print(f"\nsalesforce_status_tags.csv: {len(df)} rows")
            # Group by status label
            labels: Counter[str] = Counter()
            kinds: Counter[str] = Counter()
            for t in df[col].dropna():
                s = str(t)
                if s.startswith("(SF) UPDATED -"):
                    kinds["UPDATED"] += 1
                    m = re.match(r"\(SF\) UPDATED - (.+?) - \d{4}-\d{2}-\d{2}", s)
                    if m:
                        labels[m.group(1)] += 1
                elif s.startswith("(SF) STATUS -"):
                    kinds["STATUS"] += 1
                    m = re.match(r"\(SF\) STATUS - (.+?) - \d{4}-\d{2}-\d{2}", s)
                    if m:
                        labels[m.group(1)] += 1
            print(f"  By kind: {dict(kinds)}")
            print(f"  By status label: {dict(sorted(labels.items()))}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit REISift tags for Past-Patches cleanup")
    parser.add_argument("--export", type=Path, help="REISift contacts export CSV (needs Tags column)")
    parser.add_argument("--ingest-dir", type=Path, help="Folder with closings_status_tags.csv + salesforce_status_tags.csv")
    args = parser.parse_args()

    if not args.export and not args.ingest_dir:
        parser.error("Provide --export and/or --ingest-dir")

    if args.ingest_dir:
        print_ingest_manifest(args.ingest_dir)

    if args.export:
        df = pd.read_csv(args.export, low_memory=False)
        tags_col = next((c for c in df.columns if c.strip().lower() == "tags"), None)
        if not tags_col:
            print(f"ERROR: no Tags column in {args.export}", file=sys.stderr)
            return 1
        audit_tags_column(df[tags_col], f"REISift export: {args.export.name}")

    print("\n=== REISift bulk search (remove anything matching) ===")
    for p in REMOVE_PREFIXES:
        print(f"  starts with: {p!r}")
    print("\n=== Do NOT remove ===")
    for p in KEEP_PREFIXES:
        print(f"  starts with: {p!r}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
